### ISSUE TITLE
could you please provide some examples for trained models, ckpt

### ISSUE THREAD

**Issue by MachineGUN001** [HaotianZhangAI4Science/FragGen#1]
hi,

many thanks for providing such an interesting work!
could you please provide some examples for trained models, ckpt, eg,      ./ckpt/cartesian_val_158.pt?

thanks

best,

**Comment by MachineGUN001** [comment]
> Dear Sir, This work is awaiting publication, but I'm still happy to open-source it in advance! The trained models will be released within the next week, thanks for your interest! Warm regards, Odin

hi, Odin,

appreciate your highly productive work! look foward to your trained models and see how that works.

If you upload the preprint version available on arxiv, perhaps we can learn more about the architecture of your approach. But just from the information you have open sourced, it does make a lot of sense and has utility. I'm also curious if your method for obtaining protein surfaces is available on Windows OS?

many thanks,

Best,
Sh-Y

**Comment by HaotianZhangAI4Science** [comment]
Dear Sh-Y, 
  The development of Windos version of the protein generation program is on my to-do list. Since it relies on several other programs, it will take time to obtain the licence from their developers! I will try to accelerate this process, thanks for mentioning this thing!
Warm regards,
Odin

**Comment by HaotianZhangAI4Science** [comment]
Hi Sh-Y, 
I have uploaded the checkpoint! Feel free to contact me for any problems.
Best,
Odin

**Comment by MachineGUN001** [comment]
thank you so much!
